# This is a basic workflow to help you get started with Actions

name: gh-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "shamirova/win-indication-fix" ]
  pull_request:
    branches: [ "shamirova/win-indication-fix" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      # Runs a set of commands using the runners shell
      - name: Publish .NET Core Project
        run: dotnet publish GameSaper.Web.csproj -c Release --output release --nologo
        
      - name: Uploading files to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: release/wwwroot
